config/routes.rb
Mc437::Application.routes.draw do

  get "/tudo/:id" => "rests#tudo"
  get "/existe/:id" => "rests#existe"
  get "/cep/:id" => "rests#cep"

  resources :clients

  authenticated :admin do
    root :to => 'home#index'
  end
  root :to => "home#index"

  authenticated :operador do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :operadors

  devise_for :admins

  resources :admins, :only => [:show, :index]

  get "/clientesExcluidos" => "clients#indexEx"
  get "/clientesEstagiarios" => "clients#cliente_estagiario"
  get "/clientesPlenos" => "clients#cliente_pleno"
  get "/clientesGerentes" => "clients#cliente_gerente"
  get "/clientesSupervisores" => "clients#cliente_supervisor"
  get "/clientesDiretores" => "clients#cliente_diretor"
  get "/clientesCEOs" => "clients#cliente_ceo"
  get "/clientesCIOs" => "clients#cliente_cio"
  get "/clientesCFOs" => "clients#cliente_cfo"
  get "/clientesFinanceiros" => "clients#cliente_financeiro"
  get "/clientesConstrutoras" => "clients#cliente_construtora"
  get "/clientesComercios" => "clients#cliente_comercio"
  get "/clientesServicos" => "clients#cliente_servicos"
  get "/clientesDesempregados" => "clients#cliente_desempregado"
  get "/clientesRenda1" => "clients#cliente_renda1"
  get "/clientesRenda2" => "clients#cliente_renda2"
  get "/clientesRenda3" => "clients#cliente_renda3"
  get "/clientesRenda4" => "clients#cliente_renda4"
  get "/clientesRenda5" => "clients#cliente_renda5"
  get "/clientesRenda6" => "clients#cliente_renda6"
  get "/clientesRenda7" => "clients#cliente_renda7"
  get "/clientesEsportes" => "clients#cliente_esportes"
  get "/clientesGames" => "clients#cliente_games"
  get "/clientesTelevisao" => "clients#cliente_televisao"
  get "/clientesLeitura" => "clients#cliente_leitura"
  get "/clientesSemHobbies" => "clients#cliente_sem_hobbies"
  get "/clientesCompras" => "clients#cliente_compras"
  get "/clientesCristianismo" => "clients#cliente_cristianismo"
  get "/clientesJudaismo" => "clients#cliente_judaismo" 
  get "/clientesIslamismo" => "clients#cliente_islamismo"
  get "/clientesEspiritismo" => "clients#cliente_espiritismo"
  get "/clientesAteu" => "clients#cliente_ateu"
  get "/relatorios" => "clients#relatorios"

  get "/search" => "clients#search"
  post "/searchResult" => "clients#searchResult"
  get "/searchResult" => "clients#searchResult"

  get "/quemsomos" => "home#quemsomos"
    
  post "/restore/:id" => "clients#restore"
  get "/restore/:id" => "clients#restore"
  
  

end

app/models/client.rb
# encoding: utf-8

class Client < ActiveRecord::Base
  attr_accessible :cpf, :data_nascimento, :email, :endereco, :estado_civil_id, :hobby_id, 
  :local_nascimento, :nome, :nome_mae, :nome_pai, :observacoes, :quantidade_filhos, :religiao_id, 
  :rg, :telefone, :trabalho_area_id, :trabalho_cargo_id, :trabalho_renda_id, :ativo, :cep, :numero


  belongs_to :estado_civil
  belongs_to :hobby
  belongs_to :religiao
  belongs_to :trabalho_area
  belongs_to :trabalho_renda
  belongs_to :trabalho_cargo
  

  self.per_page = 8
  
  validate :cpf, :uniqueness => true
  validate :cpf_validation, :email_validation , :telefone_validation, :nascimento_validation
  
  
  def nascimento_validation
    puts "DATA",data_nascimento.to_s
    begin
      Date.strptime(data_nascimento.to_s,"%Y-%m-%d")
      return true
    rescue => e
      errors.add(e.message);
      return false
    end
    
  end
  
  def telefone_validation
    if telefone.size == 0 || (/([0-9]{10,11})/=~telefone)==nil
      errors.add(:telefone, ": Telefone inválido")
      return false
    end
    
    return true
  end
  
  def email_validation
    if email.size == 0 || (/\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ =~ email) == nil
      errors.add(:email , ": Email invalido")
      return false
    end
    return true
  end
  
  
  def cpf_validation
    begin
      if cpf.size !=11
        errors.add(:cpf , ": O CPF deve conter 11 dígitos")
        return false
      end
      
      mul_nums=[11,10,9,8,7,6,5,4,3,2]
      digits = cpf.chars.collect { |val| val }
      
      result = true;
      sum=0
      
      for i in 1..mul_nums.size-1
        sum=sum+mul_nums[i]*digits[i-1].to_i
      end
      
      if sum%11 < 2
        sum=0
      else
        sum=11-sum%11
      end
      
      if digits[-2].to_i != sum
        result = false
      end
        
      sum=0
      for i in 0..mul_nums.size-1
        sum=sum+mul_nums[i]*digits[i].to_i
      end
      
      if sum%11 < 2
        sum=0
      else
        sum=11-sum%11
      end
      
      if digits[-1].to_i != sum
        result = false
      end
      
      if !result
        errors.add( :cpf , ": Não é válido");
      end
      
      return result

    rescue => e
      errors.add( :cpf , ": Só são permitidos dígitos no cpf")
      return false
    end
    
  end
  # Validations
  # http://guides.rubyonrails.org/active_record_validations_callbacks.html

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  before_filter :login

  def login
    if admin_signed_in? || operador_signed_in?
      return
    else
      redirect_to new_operador_session_path
    end
  end

  def search
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @client }
    end
  end
  
  def add_item row_name, value
    if value == nil || value.size == 0
      return ""
    else
      return " and " + row_name + " = '" + value+ "'" 
    end
  end
  
  def add_like_item row_name, value
    if value == nil || value.size == 0
      return ""
    else
      return " and " + row_name + " like '%" + value+ "%'" 
    end
  end
  
  def searchResult
    @client = Client.new(params[:client])
    
    query = "(ativo) = 1"
    query+= add_item "cpf" , @client.cpf
    query+= add_like_item "nome" , @client.nome
    query+= add_item "rg" , @client.rg
    query+= add_like_item "nome_pai" , @client.nome_pai
    query+= add_like_item "nome_mae" , @client.nome_mae
    #query+= add_item "data_nascimento", @client.data_nascimento
    query+= add_like_item "local_nascimento" , @client.local_nascimento
    query+= add_item "email", @client.email
    query+= add_item "telefone", @client.telefone
    query+= add_item "quantidade_filhos", @client.quantidade_filhos
    query+= add_item "religiao_id", @client.religiao_id.to_s
    query+= add_item "hobby_id", @client.hobby_id.to_s
    query+= add_item "trabalho_area_id", @client.trabalho_area_id.to_s
    query+= add_item "trabalho_cargo_id", @client.trabalho_cargo_id.to_s
    query+= add_item "trabalho_renda_id", @client.trabalho_renda_id.to_s
    
    @clients = Client.where(query).sorted(params[:sort], :cpf)
  end
  
  # GET /clients
  # GET /clients.json
  def index
    @clients = @clients = Client.where("(ativo) = 1").sorted(params[:sort], :cpf).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def indexEx
    @clients = Client.where("(ativo) = 0").sorted(params[:sort], :cpf).page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create 
    @client = Client.new(params[:client])
    @client.ativo = true
    @client.save

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, :notice => 'Client was successfully created.' }
        format.json { render :json => @client, :status => :created, :location => @client }
      else
        format.html { render :action => "new" }
        format.json { render :json => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, :notice => 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    if @client.ativo == false
      @client.ativo = true
      @client.save

    else
      @client.ativo = false
      @client.save
    end
    
    @client.save

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  def cliente_estagiario
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_financeiro
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def relatorios
  end

  def restore
    @client = Client.find(params[:id])
    @client.ativo = 1
    @client.save
    redirect_to clientesExcluidos_path
  end

  def cliente_pleno
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_gerente
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_supervisor
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_diretor
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_ceo
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_cio
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_cfo
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_desempregado
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_comercio
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_servicos
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_construtora
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_cristianismo
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_islamismo
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_judaismo
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_ateu
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_espiritismo
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_esportes
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_games
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_televisao
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_leitura
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_compras
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_sem_hobbies
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_renda1
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_renda2
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_renda3
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_renda4
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_renda5
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  def cliente_renda6
    @clients = Client.where("(ativo) = 1")

    respond_to do |format|

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/cliente_ateu.html.erb
<div style="margin-left: 25px;">

  <h1>Lista de Clientes Estagiários</h1>

<br/>
<%= link_to 'Adicionar Cliente', new_client_path %><br/>
<%= link_to 'Voltar', root_path %>

<br/>

<div align="center">

<table class="tabela" cellpadding="2" cellspacing="1">
  <tr>
    <th><%= link_to_sorted "CPF", :cpf %></th>
    <th><%= link_to_sorted "Nome", :nome %></th>
    <th><%= link_to_sorted "RG", :rg %></th>
    <th><%= link_to_sorted "Nome do Pai", :nome_pai %></th>
    <th><%= link_to_sorted "Nome da Mãe", :nome_mae %></th>
    <th><%= link_to_sorted "Data de Nascimento", :data_nascimento%> </th>
    <th><%= link_to_sorted "Local de nascimento", :local_nascimento%></th>
    <th><%= link_to_sorted "Quantidade de filhos", :quantidade_filhos%></th>
    <th>Editar</th>
    <th>Deletar</th>
  </tr>

<% unless Religiao.first.blank? %>
  <% @clients.each do |client| %>
    <% if client.religiao.nome == "Ateu" %>
        <tr>
          <td><%= link_to client.cpf, client %></td>
          <td><%= client.nome %></td>
          <td><%= client.rg %></td>
          <td><%= client.nome_pai %></td>
          <td><%= client.nome_mae %></td>
          <td align="center"><%= client.data_nascimento.strftime("%d/%m/%y") %></td>
          <td><%= client.local_nascimento %></td>
          <td align="center"><%= client.quantidade_filhos %></td>
          <td align="center"><%= link_to 'Editar', edit_client_path(client) %></td>
          <td align="center"><%= link_to 'Deletar', client, :method => :delete, :data => { :confirm => 'Você tem certeza?' } %></td>
        </tr>
    <% end %>
  <% end %>
<% end %>
</table>

<br />

</div></div>

app/views/clients/cliente_construtora.html.erb
<div style="margin-left: 25px;">

  <h1>Lista de Clientes em Construtoras</h1>

<br/>
<%= link_to 'Adicionar Cliente', new_client_path %><br/>
<%= link_to 'Voltar', root_path %>

<br/>

<div align="center">

<table class="tabela" cellpadding="2" cellspacing="1">
  <tr>
    <th><%= link_to_sorted "CPF", :cpf %></th>
    <th><%= link_to_sorted "Nome", :nome %></th>
    <th><%= link_to_sorted "RG", :rg %></th>
    <th><%= link_to_sorted "Nome do Pai", :nome_pai %></th>
    <th><%= link_to_sorted "Nome da Mãe", :nome_mae %></th>
    <th><%= link_to_sorted "Data de Nascimento", :data_nascimento%> </th>
    <th><%= link_to_sorted "Local de nascimento", :local_nascimento%></th>
    <th><%= link_to_sorted "Quantidade de filhos", :quantidade_filhos%></th>
    <th>Editar</th>
    <th>Deletar</th>
  </tr>


<% unless TrabalhoArea.first.blank? %>
  <% @clients.each do |client| %>
    <% if client.trabalho_area.area == "Construtora" %>
        <tr>
          <td><%= link_to client.cpf, client %></td>
          <td><%= client.nome %></td>
          <td><%= client.rg %></td>
          <td><%= client.nome_pai %></td>
          <td><%= client.nome_mae %></td>
          <td align="center"><%= client.data_nascimento.strftime("%d/%m/%y") %></td>
          <td><%= client.local_nascimento %></td>
          <td align="center"><%= client.quantidade_filhos %></td>
          <td align="center"><%= link_to 'Editar', edit_client_path(client) %></td>
          <td align="center"><%= link_to 'Deletar', client, :method => :delete, :data => { :confirm => 'Você tem certeza?' } %></td>
        </tr>
    <% end %>
  <% end %>
<% end %>
</table>

<br />

  
</div></div>

app/views/clients/cliente_cristianismo.html.erb
<div style="margin-left: 25px;">

  <h1>Lista de Clientes Cristãos</h1>

<br/>
<%= link_to 'Adicionar Cliente', new_client_path %><br/>
<%= link_to 'Voltar', root_path %>

<br/>

<div align="center">

<table class="tabela" cellpadding="2" cellspacing="1">
  <tr>
    <th><%= link_to_sorted "CPF", :cpf %></th>
    <th><%= link_to_sorted "Nome", :nome %></th>
    <th><%= link_to_sorted "RG", :rg %></th>
    <th><%= link_to_sorted "Nome do Pai", :nome_pai %></th>
    <th><%= link_to_sorted "Nome da Mãe", :nome_mae %></th>
    <th><%= link_to_sorted "Data de Nascimento", :data_nascimento%> </th>
    <th><%= link_to_sorted "Local de nascimento", :local_nascimento%></th>
    <th><%= link_to_sorted "Quantidade de filhos", :quantidade_filhos%></th>
    <th>Editar</th>
    <th>Deletar</th>
  </tr>

<% unless Religiao.first.blank? %>
  <% @clients.each do |client| %>
    <% if client.religiao.nome == "Cristianismo" %>
        <tr>
          <td><%= link_to client.cpf, client %></td>
          <td><%= client.nome %></td>
          <td><%= client.rg %></td>
          <td><%= client.nome_pai %></td>
          <td><%= client.nome_mae %></td>
          <td align="center"><%= client.data_nascimento.strftime("%d/%m/%y") %></td>
          <td><%= client.local_nascimento %></td>
          <td align="center"><%= client.quantidade_filhos %></td>
          <td align="center"><%= link_to 'Editar', edit_client_path(client) %></td>
          <td align="center"><%= link_to 'Deletar', client, :method => :delete, :data => { :confirm => 'Você tem certeza?' } %></td>
        </tr>
    <% end %>
  <% end %>
<% end %>
</table>

<br />

</div></div>

app/views/clients/searchResult.html.erb
<div align="center" style="margin-left: 25px;">

  <h1>Lista de Clientes</h1>

  <br/>
  <div id="menu2">
      <%= link_to 'Adicionar Cliente', new_client_path %>
      <%= link_to 'Consultar', search_path %>
      <%= link_to 'Relatórios', relatorios_path %>
      <%= link_to 'Voltar', root_path %>
  </div>
  <!-- end of menu -->
   <br/><br/>
  <br/>

  <div align="center">

    <table class="tabela" cellpadding="2" cellspacing="1">
      <tr>
        <th><%= link_to_sorted "CPF", :cpf %></th>
        <th><%= link_to_sorted "Nome", :nome %></th>
        <th><%= link_to_sorted "RG", :rg %></th>
        <th><%= link_to_sorted "Nome do Pai", :nome_pai %></th>
        <th><%= link_to_sorted "Nome da Mãe", :nome_mae %></th>
        <th><%= link_to_sorted "Data de Nascimento", :data_nascimento%> </th>
        <th><%= link_to_sorted "Local de nascimento", :local_nascimento%></th>
        <th><%= link_to_sorted "Quantidade de filhos", :quantidade_filhos%></th>
        <th>Editar</th>
        <th>Deletar</th>
      </tr>

    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to client.cpf, client %></td>
        <td><%= client.nome %></td>
        <td><%= client.rg %></td>
        <td><%= client.nome_pai %></td>
        <td><%= client.nome_mae %></td>
        <td align="center"><%= client.data_nascimento.strftime("%d/%m/%y") %></td>
        <td><%= client.local_nascimento %></td>
        <td align="center"><%= client.quantidade_filhos %></td>
        <td align="center"><%= link_to 'Editar', edit_client_path(client) %></td>
        <td align="center"><%= link_to 'Deletar', client, :method => :delete, :data => { :confirm => 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />


    <br />
    <br />


    <table class="tabela" cellpadding="2" cellspacing="1">
      <h1>Filtros</h1>
      <tr>
        <th>Área de Trabalho</th>
        <th>Cargo</th>
        <th>Renda Mensal</th>
        <th>Hobbies</th>
        <th>Religião</th>
      </tr>

      <tr>
        <td align="center"> <%= link_to "Financeiro", clientesFinanceiros_path %> </td>
        <td align="center"> <%= link_to "Estagiário", clientesEstagiarios_path %> </td>
        <td align="center"> <%= link_to "Até 500 reais", clientesRenda1_path %> </td>
        <td align="center"> <%= link_to "Esportes", clientesEsportes_path %> </td>
        <td align="center"> <%= link_to "Cristianismo", clientesCristianismo_path %> </td>
      </tr>

      <tr>
        <td align="center"> <%= link_to "Comércio", clientesComercios_path %> </td>
        <td align="center"> <%= link_to "Pleno", clientesPlenos_path %> </td>
        <td align="center"> <%= link_to "500 a 1000 reais", clientesRenda2_path %> </td>
        <td align="center"> <%= link_to "Games", clientesGames_path %> </td>
        <td align="center"> <%= link_to "Islamismo", clientesIslamismo_path %> </td>
      </tr>

      <tr>
        <td align="center"> <%= link_to "Serviços", clientesServicos_path %> </td>
        <td align="center"> <%= link_to "Gerente", clientesGerentes_path %> </td>
        <td align="center"> <%= link_to "1000 a 2000 reais", clientesRenda3_path %> </td>
        <td align="center"> <%= link_to "Leitura", clientesLeitura_path %> </td>
        <td align="center"> <%= link_to "Judaismo", clientesJudaismo_path %> </td>
      </tr>

      <tr>
        <td align="center"> <%= link_to "Construtora", clientesConstrutoras_path %> </td>
        <td align="center"> <%= link_to "Diretor", clientesDiretores_path %> </td>
        <td align="center"> <%= link_to "2000 a 5000 reais", clientesRenda4_path %> </td>
        <td align="center"> <%= link_to "Televisão", clientesTelevisao_path %> </td>
        <td align="center"> <%= link_to "Espiritismo", clientesEspiritismo_path %> </td>
      </tr>

      <tr>
        <td align="center"> </td>
        <td align="center"> <%= link_to "CEO", clientesCEOs_path %> </td>
        <td align="center"> <%= link_to "5000 a 10000 reais", clientesRenda5_path %> </td>
        <td align="center"> <%= link_to "Compras", clientesCompras_path %> </td>
        <td align="center"> <%= link_to "Ateu", clientesAteu_path %> </td>
      </tr>

      <tr>
        <td align="center"> </td>
        <td align="center"> <%= link_to "CFO", clientesCFOs_path %> </td>
        <td align="center"> <%= link_to "10000 ou mais reais", clientesRenda6_path %> </td>
        <td align="center"> <%= link_to "Sem Hobbies", clientesSemHobbies_path %> </td>
        <td align="center"> </td>
      </tr>

      <tr>
        <td align="center"> </td>
        <td align="center"> <%= link_to "CIO", clientesCIOs_path %> </td>
        <td align="center"> <%= link_to "Sem Renda", clientesRenda7_path %> </td>
        <td align="center"> </td>
        <td align="center"> </td>
      </tr>

      <tr>
        <td align="center"> </td>
        <td align="center"> <%= link_to "Desempregado", clientesDesempregados_path %> </td>
        <td align="center"> </td>
        <td align="center"> </td>
        <td align="center"> </td>
      </tr>
    </table>


  </div>
</div>