config/routes.rb
Mc437::Application.routes.draw do

  get "/tudo/:id" => "rests#tudo"
  get "/existe/:id" => "rests#existe"
  get "/cep/:id" => "rests#cep"

  resources :clients

  authenticated :admin do
    root :to => 'home#index'
  end
  root :to => "home#index"

  authenticated :operador do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :operadors

  devise_for :admins

  resources :admins, :only => [:show, :index]

  get "/clientesExcluidos" => "clients#indexEx"
  get "/clientesEstagiarios" => "clients#cliente_estagiario"
  get "/clientesPlenos" => "clients#cliente_pleno"
  get "/clientesGerentes" => "clients#cliente_gerente"
  get "/clientesSupervisores" => "clients#cliente_supervisor"
  get "/clientesDiretores" => "clients#cliente_diretor"
  get "/clientesCEOs" => "clients#cliente_ceo"
  get "/clientesCIOs" => "clients#cliente_cio"
  get "/clientesCFOs" => "clients#cliente_cfo"
  get "/clientesFinanceiros" => "clients#cliente_financeiro"
  get "/clientesConstrutoras" => "clients#cliente_construtora"
  get "/clientesComercios" => "clients#cliente_comercio"
  get "/clientesServicos" => "clients#cliente_servicos"
  get "/clientesDesempregados" => "clients#cliente_desempregado"
  get "/clientesRenda1" => "clients#cliente_renda1"
  get "/clientesRenda2" => "clients#cliente_renda2"
  get "/clientesRenda3" => "clients#cliente_renda3"
  get "/clientesRenda4" => "clients#cliente_renda4"
  get "/clientesRenda5" => "clients#cliente_renda5"
  get "/clientesRenda6" => "clients#cliente_renda6"
  get "/clientesRenda7" => "clients#cliente_renda7"
  get "/clientesEsportes" => "clients#cliente_esportes"
  get "/clientesGames" => "clients#cliente_games"
  get "/clientesTelevisao" => "clients#cliente_televisao"
  get "/clientesLeitura" => "clients#cliente_leitura"
  get "/clientesSemHobbies" => "clients#cliente_sem_hobbies"
  get "/clientesCompras" => "clients#cliente_compras"
  get "/clientesCristianismo" => "clients#cliente_cristianismo"
  get "/clientesJudaismo" => "clients#cliente_judaismo" 
  get "/clientesIslamismo" => "clients#cliente_islamismo"
  get "/clientesEspiritismo" => "clients#cliente_espiritismo"
  get "/clientesAteu" => "clients#cliente_ateu"
  get "/relatorios" => "clients#relatorios"

  get "/search" => "clients#search"
  post "/searchResult" => "clients#searchResult"
  get "/searchResult" => "clients#searchResult"

  get "/quemsomos" => "home#quemsomos"
    
  post "/restore/:id" => "clients#restore"
  get "/restore/:id" => "clients#restore"
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MC437 - Grupo 01 - Clientes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= yield (:charts) %>


</head>
<body>


<div id="wrapper_outter">
  <div id="wrapper_inner">
    <div id="wrapper">
      <div id="container">



        <div align="right" style=" margin-right: 25px; ">
          <% if admin_signed_in? %>
            <div>Seja bem vindo, ADMIN</div>
            <%= button_to 'Sair', destroy_admin_session_path, :method => :delete %>
          <% end %>

          <% if operador_signed_in? %>
            <div>Seja bem vindo, OPERADOR</div>
            <%= button_to 'Sair', destroy_operador_session_path, :method => :delete %>
          <% end %>
        </div>


        <div id="header">
          <div id="header_left">

            <div id="site_title" align = "left">
              <h1> <img src="/assets/logo.png" alt=""/></h1>
            </div>
            <div id="menu">
              <ul>

                <li><a href="/" class="current">Home</a></li>

                <% if admin_signed_in? %>
                  <li><a href="/clients">Ver Clientes</a></li>
                  <li><a href="/clientesExcluidos">Clientes Excluídos</a></li>
                <% else %>
                  <% unless operador_signed_in? %>
                    <li><a href="/admins/sign_in">Admin Login</a></li>
                  <% end %>
                <% end %>

                <% if operador_signed_in? %>
                  <li><a href="/clients">Ver Clientes</a></li>
                <% else %>
                  <% unless admin_signed_in? %>
                    <li><a href="/operadors/sign_in">Operador Login</a></li>
                  <% end %>
                <% end %>

                <li><a href="/quemsomos">Quem somos</a></li>

              </ul>
            </div>
            <!-- end of menu -->
          </div> 
          <div class="cleaner"></div>
        </div>
        <!-- end of header -->


<%= yield %>




        <div id="footer">
          Copyright &copy; 2012 <a href="http://mc437-clientes.herokuapp.com/">Componente Cliente - MC437</a> | Desenvolvido por Alexandre Creto, Fernando Lener, Gregori Inagaki, Murilo Travareli e Piergiorgio Lisanti.</div>
        <!-- end of footer -->
        <div class="cleaner"></div>
      </div>
    </div>
  </div>
</div>





</body>
</html>